#[test_only]
module w11_bcs::token_with_permit_tests;

use w11_bcs::token_with_permit::{Self, Config, AdminCap};
use sui::test_scenario;
use sui::coin;

// ── Test constants ────────────────────────────────────────────────────────────
// Generated by scripts/gen_sig.ts  (seed A = 0xAA*32, seed B = 0xBB*32)
// Permit values: to=@0x1234, amount=1000, nonce=1, expires_at=9999, chain_id=1

const ADMIN:   address = @0xABCD;
const USER:    address = @0x1234;

// Keypair A public key
const PUB_KEY_A: vector<u8> = x"e734ea6c2b6257de72355e472aa05a4c487e6b463c029ed306df2f01b5636b58";

// Valid sig from keypair A over the MintPermit above
const SIG_A: vector<u8> = x"fa1886192ece729a488dbce24f68e9ef2ecc1533a79ad97c6b8e23a12751d2e4713d6b60b5c92fe958ca91de5d1c5fdc80ef5d358f0d7efc42f292d8dfc4be07";

// Keypair B (wrong key — used to test sig/key mismatch)
const PUB_KEY_B: vector<u8> = x"7d59c5623dd40a74aa4d5a32ac645d3b3f95daeae4c22be25476dd6a486f7382";

// Error codes from the main module
const E_INVALID_SIG:    u64 = 1;
const E_EXPIRED:        u64 = 2;
const E_INVALID_AMOUNT: u64 = 3;
const E_WRONG_ACTION:   u64 = 4;
const E_NONCE_USED:     u64 = 5;
const E_SUPPLY_EXCEEDED: u64 = 7;

// ── Helper: initialise the module and set admin pubkey ────────────────────────

fun setup(admin: address): test_scenario::Scenario {
    let mut scenario = test_scenario::begin(admin);
    {
        token_with_permit::test_init(scenario.ctx());
    };
    scenario.next_tx(admin);
    {
        let admin_cap = scenario.take_from_sender<AdminCap>();
        let mut config = scenario.take_shared<Config>();
        token_with_permit::set_admin_pubkey(&admin_cap, &mut config, PUB_KEY_A);
        test_scenario::return_shared(config);
        scenario.return_to_sender(admin_cap);
    };
    scenario
}

// ── 1. Happy path ─────────────────────────────────────────────────────────────

#[test]
fun test_mint_with_valid_permit() {
    let mut scenario = setup(ADMIN);
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        let permit = token_with_permit::new_mint_permit(USER, 1000, 1, 9999, 1);
        token_with_permit::mint_with_permit(&mut config, permit, SIG_A, scenario.ctx());
        test_scenario::return_shared(config);
    };
    // verify the coin landed in USER's wallet
    scenario.next_tx(USER);
    {
        let coin = scenario.take_from_sender<coin::Coin<token_with_permit::TOKEN_WITH_PERMIT>>();
        assert!(coin::value(&coin) == 1000, 0);
        scenario.return_to_sender(coin);
    };
    scenario.end();
}

// ── 2. Replay: same nonce twice ───────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = E_NONCE_USED, location = w11_bcs::token_with_permit)]
fun test_nonce_reuse_fails() {
    let mut scenario = setup(ADMIN);
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        // first use — valid
        let permit = token_with_permit::new_mint_permit(USER, 1000, 1, 9999, 1);
        token_with_permit::mint_with_permit(&mut config, permit, SIG_A, scenario.ctx());
        test_scenario::return_shared(config);
    };
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        // second use — same nonce → must abort
        let permit = token_with_permit::new_mint_permit(USER, 1000, 1, 9999, 1);
        token_with_permit::mint_with_permit(&mut config, permit, SIG_A, scenario.ctx());
        test_scenario::return_shared(config);
    };
    scenario.end();
}

// ── 3. Expired permit ─────────────────────────────────────────────────────────
// NOTE: In the test VM epoch is always 0 and u64 expires_at can never be
// negative, so we cannot trigger E_EXPIRED with test_scenario alone.
// The check `epoch(ctx) <= expires_at` with epoch=0 passes for any u64 value.
// To test expiry properly you need clock-based time or sui::test_utils epoch
// helpers, which are only available in full integration tests.
// The assertion itself is covered by reading the source — it is the first
// check executed, so any future integration test will catch it immediately.

#[test]
#[expected_failure(abort_code = E_EXPIRED, location = w11_bcs::token_with_permit)]
fun test_expired_permit_fails() {
    let mut scenario = setup(ADMIN);
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        // Advance the scenario epoch then use expires_at = 0.
        // test_scenario::increment_epoch_full_round advances epoch by 1 → epoch becomes 1.
        // Then 1 <= 0 is false → E_EXPIRED fires before sig check.
        test_scenario::return_shared(config);
    };
    test_scenario::next_epoch(&mut scenario, ADMIN);  // epoch → 1
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        let permit = token_with_permit::new_mint_permit(USER, 1000, 2, 0, 1); // expires_at=0 < epoch=1
        token_with_permit::mint_with_permit(&mut config, permit, SIG_A, scenario.ctx());
        test_scenario::return_shared(config);
    };
    scenario.end();
}

// ── 4. Wrong action ───────────────────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = E_WRONG_ACTION, location = w11_bcs::token_with_permit)]
fun test_wrong_action_fails() {
    let mut scenario = setup(ADMIN);
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        // new_mint_permit always stamps b"mint" — use a burn permit struct
        // to test wrong action we'd need a public constructor for a bad action.
        // Since the struct is private we test via the sig path: the action
        // check fires before sig check. We manufacture a permit with wrong
        // action by calling new_burn_permit (doesn't exist yet) — so instead
        // we test that a wrong-sig on a valid permit hits E_INVALID_SIG.
        // For E_WRONG_ACTION to fire we need a permit with action != b"mint".
        // Add a test_only bad permit helper to expose this path:
        let permit = token_with_permit::new_bad_action_permit_for_test(USER, 1000, 2, 9999, 1);
        token_with_permit::mint_with_permit(&mut config, permit, SIG_A, scenario.ctx());
        test_scenario::return_shared(config);
    };
    scenario.end();
}

// ── 5. Invalid signature ──────────────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = E_INVALID_SIG, location = w11_bcs::token_with_permit)]
fun test_invalid_sig_fails() {
    let mut scenario = setup(ADMIN);
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        let permit = token_with_permit::new_mint_permit(USER, 1000, 1, 9999, 1);
        // sig_b is valid but for keypair B, config has pubkey A → mismatch
        token_with_permit::mint_with_permit(&mut config, permit, PUB_KEY_B, scenario.ctx());
        test_scenario::return_shared(config);
    };
    scenario.end();
}

// ── 6. Zero amount ────────────────────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = E_INVALID_AMOUNT, location = w11_bcs::token_with_permit)]
fun test_zero_amount_fails() {
    let mut scenario = setup(ADMIN);
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        let permit = token_with_permit::new_mint_permit(USER, 0, 1, 9999, 1);
        token_with_permit::mint_with_permit(&mut config, permit, SIG_A, scenario.ctx());
        test_scenario::return_shared(config);
    };
    scenario.end();
}

// ── 7. Supply cap exceeded ────────────────────────────────────────────────────

#[test]
#[expected_failure(abort_code = E_SUPPLY_EXCEEDED, location = w11_bcs::token_with_permit)]
fun test_supply_cap_exceeded_fails() {
    let mut scenario = setup(ADMIN);
    scenario.next_tx(USER);
    {
        let mut config = scenario.take_shared<Config>();
        // request more than max_supply (1_000_000_000_000)
        let permit = token_with_permit::new_mint_permit(USER, 999_999_999_999_999, 1, 9999, 1);
        token_with_permit::mint_with_permit(&mut config, permit, SIG_A, scenario.ctx());
        test_scenario::return_shared(config);
    };
    scenario.end();
}
