[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "BHTeQ5JTo164bHQaiE1thJsGaQRmDz1BMZRqHNbC5VF8"
[programs.devnet]
hello_anchor = "BHTeQ5JTo164bHQaiE1thJsGaQRmDz1BMZRqHNbC5VF8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
