#[test_only]
module w11_bcs_hash::hash_demo_tests;

use w11_bcs_hash::hash_demo;
use sui::bcs;

// ── helpers ──────────────────────────────────────────────────────────────────

fun make_demo(): hash_demo::HashDemo {
    hash_demo::new(@0xAAAA, @0xBBBB, 1_000_000)
}

// ── BCS roundtrip ─────────────────────────────────────────────────────────────

#[test]
fun test_bcs_roundtrip() {
    let original = make_demo();
    // encode to bytes
    let bytes = bcs::to_bytes(&original);
    // decode back
    let decoded = hash_demo::from_bytes(bytes);
    // fields must match
    assert!(hash_demo::from(&decoded) == @0xAAAA, 0);
    assert!(hash_demo::to(&decoded)   == @0xBBBB, 1);
    assert!(hash_demo::amount(&decoded) == 1_000_000, 2);
}

#[test]
fun test_bcs_field_order_matters() {
    // BCS is NOT self-describing — field order in the struct drives the layout.
    // If we decoded swapping from/to we would get garbage.
    // Here we just verify the encoded length is exactly 32+32+8 = 72 bytes.
    let demo = make_demo();
    let bytes = bcs::to_bytes(&demo);
    assert!(bytes.length() == 72, 0);
}

// ── Hashing ───────────────────────────────────────────────────────────────────

#[test]
fun test_keccak256_is_deterministic() {
    let h1 = hash_demo::to_keccak256(make_demo());
    let h2 = hash_demo::to_keccak256(make_demo());
    assert!(h1 == h2, 0);
    // keccak256 always produces 32 bytes
    assert!(h1.length() == 32, 1);
}

#[test]
fun test_sha256_is_deterministic() {
    let h1 = hash_demo::to_sha256(make_demo());
    let h2 = hash_demo::to_sha256(make_demo());
    assert!(h1 == h2, 0);
    // sha2_256 always produces 32 bytes
    assert!(h1.length() == 32, 1);
}

#[test]
fun test_keccak256_and_sha256_differ() {
    // Same input, different algorithms → different digests
    let keccak = hash_demo::to_keccak256(make_demo());
    let sha    = hash_demo::to_sha256(make_demo());
    assert!(keccak != sha, 0);
}

#[test]
fun test_different_amounts_produce_different_hashes() {
    let demo1 = hash_demo::new(@0xAAAA, @0xBBBB, 100);
    let demo2 = hash_demo::new(@0xAAAA, @0xBBBB, 200);
    let h1 = hash_demo::to_keccak256(demo1);
    let h2 = hash_demo::to_keccak256(demo2);
    assert!(h1 != h2, 0);
}

// ── Compatibility checks ──────────────────────────────────────────────────────

#[test]
fun test_is_evm_compatible_true() {
    let demo = make_demo();
    // compute the expected hash first, then check
    let expected = hash_demo::to_keccak256(make_demo());
    assert!(hash_demo::is_EVM_compatible(expected, demo), 0);
}

#[test]
fun test_is_evm_compatible_false_with_wrong_hash() {
    let demo = make_demo();
    let wrong_hash = x"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef";
    assert!(!hash_demo::is_EVM_compatible(wrong_hash, demo), 0);
}

#[test]
fun test_is_sui_compatible_true() {
    let demo = make_demo();
    let expected = hash_demo::to_sha256(make_demo());
    assert!(hash_demo::is_Sui_compatible(expected, demo), 0);
}

#[test]
fun test_is_sui_compatible_false_with_wrong_hash() {
    let demo = make_demo();
    let wrong_hash = x"cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe";
    assert!(!hash_demo::is_Sui_compatible(wrong_hash, demo), 0);
}

#[test]
fun test_evm_hash_does_not_pass_sui_check() {
    // keccak256 digest must not equal sha256 digest → cross-algorithm mismatch
    let demo = make_demo();
    let keccak_hash = hash_demo::to_keccak256(make_demo());
    assert!(!hash_demo::is_Sui_compatible(keccak_hash, demo), 0);
}

// ── Signature (valid — pre-computed with gen_sig.ts) ─────────────────────────

#[test]
fun test_valid_signature_keypair_a() {
    // Keypair A: seed = 0xAA * 32  (generated by scripts/gen_sig.ts)
    let hash    = x"c01b3544e29b890ec8c9e837ca89b4e345bbd954a71d546dcc58cd065b4f2198";
    let pub_key = x"e734ea6c2b6257de72355e472aa05a4c487e6b463c029ed306df2f01b5636b58";
    let sig     = x"68ea85b0ef59db0eb8b2732486c2267de8c03a1c07d7634e47deaeccaf18b1a101dd6a335db910f1acb47a9d6361ebe241020520cb3c72a1997017f17771c908";
    assert!(hash_demo::is_valid_signature(hash, make_demo(), sig, pub_key), 0);
}

#[test]
fun test_valid_signature_keypair_b() {
    // Keypair B: seed = 0xBB * 32  (generated by scripts/gen_sig.ts)
    let hash    = x"c01b3544e29b890ec8c9e837ca89b4e345bbd954a71d546dcc58cd065b4f2198";
    let pub_key = x"7d59c5623dd40a74aa4d5a32ac645d3b3f95daeae4c22be25476dd6a486f7382";
    let sig     = x"52f1901a69e16d53c40bae43880d6b364c7c4735b6b04d88c604c92c0fba60231e8ee3ac2285b5fefa89fcc944e4a00470f606be939faecdc469f9315683680a";
    assert!(hash_demo::is_valid_signature(hash, make_demo(), sig, pub_key), 0);
}

// ── Signature (wrong key must not verify) ─────────────────────────────────────

#[test]
fun test_sig_a_does_not_verify_with_key_b() {
    // Sig from keypair A must not verify against keypair B's public key.
    let hash    = x"c01b3544e29b890ec8c9e837ca89b4e345bbd954a71d546dcc58cd065b4f2198";
    let pub_key_b = x"7d59c5623dd40a74aa4d5a32ac645d3b3f95daeae4c22be25476dd6a486f7382";
    let sig_a   = x"68ea85b0ef59db0eb8b2732486c2267de8c03a1c07d7634e47deaeccaf18b1a101dd6a335db910f1acb47a9d6361ebe241020520cb3c72a1997017f17771c908";
    assert!(!hash_demo::is_valid_signature(hash, make_demo(), sig_a, pub_key_b), 0);
    // @audit :  All-zero key + all-zero signature verifies as true (passes).
    let bad_sig = x"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    let bad_key = x"0000000000000000000000000000000000000000000000000000000000000000";
    assert!(hash_demo::is_valid_signature(hash, make_demo(), bad_sig, bad_key), 0);

}
